In [32]:
!nvidia-smi

Sat May 23 14:07:13 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [33]:
!pip install -q google-genai pdf2image pillow pandas fuzzywuzzy python-Levenshtein
!pip install fuzzywuzzy python-Levenshtein
!pip install pdfplumber
import json
import os
import pandas as pd
from fuzzywuzzy import fuzz
from itertools import product

Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.12/dist-packages (0.18.0)
Requirement already satisfied: python-Levenshtein in /usr/local/lib/python3.12/dist-packages (0.27.3)
Requirement already satisfied: Levenshtein==0.27.3 in /usr/local/lib/python3.12/dist-packages (from python-Levenshtein) (0.27.3)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from Levenshtein==0.27.3->python-Levenshtein) (3.14.5)
Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.9)
Requirement already satisfied: pdfminer.six==20251230 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.8.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.7)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)

In [34]:
from google.colab import drive
drive.mount('/content/drive')

# 🔧 Change this to your actual folder path
DATA_DIR = '/content/drive/MyDrive/magriplast'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [35]:
# Mise à jour du chemin vers le dossier identifié dans le Drive
DATA_DIR = '/content/drive/MyDrive/magriplast'

In [36]:
!ls /content/drive/MyDrive

'Colab Notebooks'
 magriplast
 ph5_colect.zip
'RAPPORT D'\''AUDIT TECHNIQUE : SÉCURITÉ RÉSEAU ET PÉRIMÈTRE (PHASE 2).gdoc'

In [37]:
!ls -F /content/drive/MyDrive/magriplast

20260302_12105033.pdf  20260302_12181839.pdf  20260302_12260491.pdf
20260302_12115701.pdf  20260302_12185159.pdf

In [38]:

import os
import json
import time
from getpass import getpass

from google import genai
from google.genai import types
from pdf2image import convert_from_path
import pandas as pd
from fuzzywuzzy import fuzz

# --- Gemini API key ---
# You can paste it directly (less secure) or enter interactively
GEMINI_API_KEY = getpass("Enter your Gemini API key: ")

client = genai.Client(api_key=GEMINI_API_KEY)
model_name = "gemini-2.5-flash"  # or gemini-2.5-pro if needed

Enter your Gemini API key: ··········

In [39]:
def extract_page_lines(image, page_num):
    """
    Sends a page image to Gemini and returns a list of line items.
    Each item is a dict with keys:
      ref, designation, qty, prix_unitaire, doc_type
    """
    prompt = """You are an OCR and data extraction assistant for French/Tunisian business documents.
Look at the page image and return ALL product line items in strict JSON format.

For each line item, include:
  - "ref": the article/product reference code exactly as printed (can be null if not visible)
  - "designation": the product description
  - "qty": quantity (number)
  - "prix_unitaire": unit price in TND (number, 3 decimal places)
  - "doc_type": "BC" if the page is a purchase order / bon de commande,
                "FACTURE" if it is an invoice,
                "UNKNOWN" if unclear

Return ONLY a JSON array of objects, nothing else.
Example: [{"ref":"P123456","designation":"BUTEE A RLX","qty":4,"prix_unitaire":122.341,"doc_type":"BC"}]
"""

    try:
        response = client.models.generate_content(
            model=model_name,
            contents=[prompt, image],
            config=types.GenerateContentConfig(
                temperature=0.0,
                max_output_tokens=8192,
                response_mime_type="application/json",
            ),
        )
        raw_text = response.text.strip()
        # Parse JSON
        data = json.loads(raw_text)
        if isinstance(data, list):
            for item in data:
                item.setdefault("ref", None)
                item.setdefault("designation", "")
                item.setdefault("qty", None)
                item.setdefault("prix_unitaire", None)
                item.setdefault("doc_type", "UNKNOWN")
            return data
        else:
            print(f"Page {page_num}: unexpected JSON structure")
            return []
    except Exception as e:
        print(f"Page {page_num}: Gemini error - {e}")
        return []

In [40]:
all_lines = []

pdf_files = [f for f in os.listdir(DATA_DIR) if f.lower().endswith('.pdf')]
print(f"Found {len(pdf_files)} PDF files")

for idx, pdf_name in enumerate(pdf_files):
    pdf_path = os.path.join(DATA_DIR, pdf_name)
    print(f"\n[{idx+1}/{len(pdf_files)}] Processing: {pdf_name}")

    try:
        # Convert PDF pages to images (300 DPI for readability)
        images = convert_from_path(pdf_path, dpi=300)
    except Exception as e:
        print(f"  ❌ Could not convert PDF: {e}")
        continue

    for page_num, img in enumerate(images):
        print(f"  Page {page_num+1}/{len(images)} ...", end="")
        lines = extract_page_lines(img, page_num+1)
        if lines:
            for item in lines:
                item["source_pdf"] = pdf_name
                item["page"] = page_num + 1
            all_lines.extend(lines)
            print(f" {len(lines)} lines extracted")
        else:
            print(" no lines found")
        # Small delay to respect rate limits (adjust as needed)
        time.sleep(1)

print(f"\n✅ Extraction complete. Total lines collected: {len(all_lines)}")

Found 5 PDF files

[1/5] Processing: 20260302_12115701.pdf
  Page 1/3 ... 9 lines extracted
  Page 2/3 ... 12 lines extracted
  Page 3/3 ... no lines found

[2/5] Processing: 20260302_12185159.pdf
  Page 1/6 ... 1 lines extracted
  Page 2/6 ... 2 lines extracted
  Page 3/6 ... 1 lines extracted
  Page 4/6 ... 2 lines extracted
  Page 5/6 ... 2 lines extracted
  Page 6/6 ... 4 lines extracted

[3/5] Processing: 20260302_12105033.pdf
  Page 1/8 ... 20 lines extracted
  Page 2/8 ... 20 lines extracted
  Page 3/8 ... no lines found
  Page 4/8 ... 20 lines extracted
  Page 5/8 ... 5 lines extracted
  Page 6/8 ... 6 lines extracted
  Page 7/8 ... 6 lines extracted
  Page 8/8 ... 5 lines extracted

[4/5] Processing: 20260302_12181839.pdf
  Page 1/9 ... 11 lines extracted
  Page 2/9 ... 5 lines extracted
  Page 3/9 ... 5 lines extracted
  Page 4/9 ... 2 lines extracted
  Page 5/9 ... 2 lines extracted
  Page 6/9 ... 4 lines extracted
  Page 7/9 ... 4 lines extracted
  Page 8/9 ... 4 lines extracted
  Page 9/9 ... 7 lines extracted

[5/5] Processing: 20260302_12260491.pdf
  Page 1/6 ... 2 lines extracted
  Page 2/6 ... 1 lines extracted
  Page 3/6 ... 1 lines extracted
  Page 4/6 ... 1 lines extracted
  Page 5/6 ... 2 lines extracted
  Page 6/6 ... 2 lines extracted

✅ Extraction complete. Total lines collected: 168

In [41]:
df = pd.DataFrame(all_lines)
print(f"Columns: {list(df.columns)}")
print(f"Doc types found: {df['doc_type'].value_counts().to_dict()}")
df.head()

Columns: ['ref', 'designation', 'qty', 'prix_unitaire', 'doc_type', 'source_pdf', 'page']
Doc types found: {'UNKNOWN': 65, 'FACTURE': 54, 'BC': 49}

,ref,designation,qty,prix_unitaire,doc_type,source_pdf,page
0,2019005,MW UNION = TECHNOPOLYMERE,10.0,5.568,FACTURE,20260302_12115701.pdf,1
1,NPC12-02,SHAKO RACCORD DROIT 12 1/4,10.0,6.207,FACTURE,20260302_12115701.pdf,1
2,NPC10-04,SHAKO RACC DROIT 10 1/2 EQ 2L01,5.0,7.752,FACTURE,20260302_12115701.pdf,1
3,NPC8-04,SHAKO RACCORD DROIT 8 1/2,5.0,6.821,FACTURE,20260302_12115701.pdf,1
4,PU1080BL,CAM TUBE 10X8 BLEU,20.0,4.339,FACTURE,20260302_12115701.pdf,1

In [56]:
# --- Pair BC ↔ Facture per PDF (tolerant) ---
alias_pairs = []

for pdf_name, group in df.groupby('source_pdf'):
    bc_lines = group[group['doc_type'] == 'BC']
    fac_lines = group[group['doc_type'] == 'FACTURE']
    if bc_lines.empty or fac_lines.empty:
        continue

    for idx_bc, bc_row in bc_lines.iterrows():
        best_score = 0
        best_fac = None
        for idx_fac, fac_row in fac_lines.iterrows():
            # Quantity match with small tolerance
            if (bc_row['qty'] is None or fac_row['qty'] is None or
                abs(float(bc_row['qty']) - float(fac_row['qty'])) > 0.5):
                continue
            # Price match with small tolerance (TND)
            if (bc_row['prix_unitaire'] is None or fac_row['prix_unitaire'] is None or
                abs(float(bc_row['prix_unitaire']) - float(fac_row['prix_unitaire'])) > 0.02):
                continue

            # Fuzzy designation score (still useful for confidence)
            score = fuzz.token_sort_ratio(
                str(bc_row['designation']).lower(),
                str(fac_row['designation']).lower()
            )
            if score > best_score:
                best_score = score
                best_fac = fac_row

        # Lower threshold to 50, also accept pairs with exact qty/price even if low score
        if best_fac is not None and (best_score >= 50):
            alias_pairs.append({
                'pdf': pdf_name,
                'internal_ref': bc_row['ref'],
                'external_ref': best_fac['ref'],
                'designation': bc_row['designation'],
                'qty': bc_row['qty'],
                'prix': bc_row['prix_unitaire'],
                'match_score': best_score
            })

aliases_df = pd.DataFrame(alias_pairs)
print(f"Candidate alias pairs: {len(aliases_df)}")
# Keep only where refs differ
aliases_df = aliases_df[aliases_df['internal_ref'] != aliases_df['external_ref']]
print(f"After removing identical refs: {len(aliases_df)}")
# Deduplicate
aliases_df = aliases_df.sort_values('match_score', ascending=False)
aliases_df = aliases_df.drop_duplicates(subset=['internal_ref', 'external_ref'], keep='first')
aliases_df.reset_index(drop=True, inplace=True)
aliases_df.head(20)
# --- Add known aliases that might still be missing ---
verified = [
    {'pdf':'20260302_12115701.pdf', 'internal_ref':'P199420414', 'external_ref':'81105 TN',
     'designation':'BUTEE A RLX CYLIND', 'qty':4.0, 'prix':122.341, 'match_score':100},
    {'pdf':'20260302_12115701.pdf', 'internal_ref':'P199420416', 'external_ref':'NKX 25 Z',
     'designation':'RLT A AIG AVEC BUTEE', 'qty':4.0, 'prix':242.200, 'match_score':100},
    {'pdf':'20260302_12115701.pdf', 'internal_ref':'P199684214', 'external_ref':'2019005',
     'designation':'SHAKO UNION TECHNOPOLYMERE', 'qty':10.0, 'prix':5.568, 'match_score':100},
]
verified_df = pd.DataFrame(verified)
aliases_df = pd.concat([aliases_df, verified_df], ignore_index=True)
aliases_df = aliases_df.drop_duplicates(subset=['internal_ref', 'external_ref'], keep='first')
aliases_df = aliases_df.sort_values('match_score', ascending=False).reset_index(drop=True)
print(f"Total aliases after adding verified: {len(aliases_df)}")

Candidate alias pairs: 37
After removing identical refs: 37
Total aliases after adding verified: 37

In [57]:
# --- Clean external refs: remove spaces, standardize ---
aliases_df['external_ref'] = aliases_df['external_ref'].str.replace(' ', '').str.upper()
aliases_df['internal_ref'] = aliases_df['internal_ref'].str.replace(' ', '').str.upper()

# Remove duplicates again after cleaning
aliases_df = aliases_df.drop_duplicates(subset=['internal_ref', 'external_ref'], keep='first')
aliases_df = aliases_df.sort_values('match_score', ascending=False).reset_index(drop=True)

print(f"Final aliases after cleaning: {len(aliases_df)}")
display(aliases_df[['external_ref', 'internal_ref', 'designation', 'qty', 'prix', 'match_score']])

Final aliases after cleaning: 37

,external_ref,internal_ref,designation,qty,prix,match_score
0,8020137,P199680105,DECAPANT 5L,1.0,30.300,100
1,PU1080BL,P199681847,CAM TUBE 10X8 BLEU,20.0,4.339,100
2,RACCORD,P199600771,RACCORD S16 male 1/2,8.0,12.000,100
3,8012599,P199692133,SILICONE SIKAFLEX CRISTAL,1.0,34.252,100
4,NKX25Z,P199420416,RLT A AIG AVEC BUTEE,4.0,242.200,100
5,COLLIER,P199680428,COLLIER DE SERRAGE A BOULON DN 80/85,4.0,15.000,95
6,6050004,P199680440,RIVET ALLU 4.8*22,250.0,0.098,94
7,NPC8-04,P199450101,SHAKO RACC DROIT 8 1/2,5.0,6.821,94
8,NPC12-02,P199450265,SHAKO RACC DROIT 12 1/4,10.0,6.207,94
9,COLLIER,P199681803,COLLIER DE SERRAGE A BOULON DN 23/35,10.0,4.000,92
10,BCF04H,P199403539,MECHE ACIER RECTIFIE 4MM,2.0,0.938,90
11,BCF05H,P199403542,MECHE ACIER RECTIFIE 5MM,5.0,1.366,90
12,FLEXSM,P199600774,"FLEX EAU R2AT DN 3/8"" LG 1000 F/FC 90°",2.0,69.000,90
13,1-947,P199680240,JEUX 9 CLE MALE LONG 1.5-10MM,1.0,49.132,90
14,PU225S-04-S2,P199685061,SHAKO ELECTROANNE 2/2 1/4,1.0,240.278,89
15,TUYAU,P199600770,TUYAU ARME DN 16,20.0,25.000,88
16,FLEXSM,P199600773,"FLEX DE GRAISSE DN 1/4"" LG 1260 F/FC 90°",2.0,79.500,87
17,2030521,P199403517,TIGE GALVA DE24,1.0,28.382,85
18,NPC10-04,P199450136,SHAKO RACC DROIT 10 1/2,5.0,7.752,85
19,OSV,P199680434,TUY GORGE OSV DN 38,10.0,15.000,85
20,Z10100,P199450235,SHAKO TEMPORISATEUR Z10100,1.0,109.943,84
21,6030272-27,P199403654,RONDELLE PLATE GALV M6/27,50.0,0.072,83
22,TUYAU,P199680433,"TUY R4 DN 1"" 1/4",20.0,50.000,82
23,COLLIER,P199600363,COLLIER DE SERRAGE DN 44/47,20.0,5.000,80
24,TUYAU,P199600772,TUYAU OSV DN75,10.0,30.000,77
25,643000,P199403555,VIS TH GAL CL 8.8 M 12*40,30.0,0.578,77
26,4032185,P199680136,DISQUE A LAMELLE 115*22.23 Z60 SPEC: BL2460/2025,2.0,4.695,73
27,7020096,P199662040,GUANT DE TRAVAIL T10,1.0,3.894,71
28,920644000,P199403496,VIS TH GAL 8.8 M 10*40,30.0,0.519,70
29,77600,P199602123,CADNA BLOCUS LAITON 60MM ref 77600,1.0,9.440,64
30,DW36PT,P199681231,JEUX TARRAUD M24,1.0,330.000,62
31,2019005,P199684214,SHAKO UNION TECHNOPOLYMERE SPEC: BL/LA25/01983,10.0,5.568,62
32,3121,P199642013,CHAINE ACIER 21-5MM,1.0,4.520,61
33,3787,P199662039,ARALDIT 2*15ML,1.0,32.303,61
34,2110160,P199602050,CADNA BLOCUS LAITON 60MM REF 2110160,2.0,45.081,57
35,81105TN,P199420414,BUTEE A RLX CYLIND ref 81105TN SPEC: BL/LR25/0...,4.0,122.341,56
36,1019016,P199680439,RIVET POP 4*12.7,1000.0,0.046,54

In [58]:
print("\n=== Proposed alias mappings (external → internal) ===\n")
for _, row in aliases_df.iterrows():
    print(f"{row['external_ref']}  →  {row['internal_ref']}  "
          f"(score: {row['match_score']}%)  [{row['designation'][:60]}...]")

=== Proposed alias mappings (external → internal) ===

8020137  →  P199680105  (score: 100%)  [DECAPANT 5L...]
PU1080BL  →  P199681847  (score: 100%)  [CAM TUBE 10X8 BLEU...]
RACCORD  →  P199600771  (score: 100%)  [RACCORD S16 male 1/2...]
8012599  →  P199692133  (score: 100%)  [SILICONE SIKAFLEX CRISTAL...]
NKX25Z  →  P199420416  (score: 100%)  [RLT A AIG AVEC BUTEE...]
COLLIER  →  P199680428  (score: 95%)  [COLLIER DE SERRAGE A BOULON DN 80/85...]
6050004  →  P199680440  (score: 94%)  [RIVET ALLU 4.8*22...]
NPC8-04  →  P199450101  (score: 94%)  [SHAKO RACC DROIT 8 1/2...]
NPC12-02  →  P199450265  (score: 94%)  [SHAKO RACC DROIT 12 1/4...]
COLLIER  →  P199681803  (score: 92%)  [COLLIER DE SERRAGE A BOULON DN 23/35...]
BCF04H  →  P199403539  (score: 90%)  [MECHE ACIER RECTIFIE 4MM...]
BCF05H  →  P199403542  (score: 90%)  [MECHE ACIER RECTIFIE 5MM...]
FLEXSM  →  P199600774  (score: 90%)  [FLEX EAU R2AT DN 3/8" LG 1000 F/FC 90°...]
1-947  →  P199680240  (score: 90%)  [JEUX 9 CLE MALE LONG 1.5-10MM...]
PU225S-04-S2  →  P199685061  (score: 89%)  [SHAKO ELECTROANNE 2/2 1/4...]
TUYAU  →  P199600770  (score: 88%)  [TUYAU ARME DN 16...]
FLEXSM  →  P199600773  (score: 87%)  [FLEX DE GRAISSE DN 1/4" LG 1260 F/FC 90°...]
2030521  →  P199403517  (score: 85%)  [TIGE GALVA DE24...]
NPC10-04  →  P199450136  (score: 85%)  [SHAKO RACC DROIT 10 1/2...]
OSV  →  P199680434  (score: 85%)  [TUY GORGE OSV DN 38...]
Z10100  →  P199450235  (score: 84%)  [SHAKO TEMPORISATEUR Z10100...]
6030272-27  →  P199403654  (score: 83%)  [RONDELLE PLATE GALV M6/27...]
TUYAU  →  P199680433  (score: 82%)  [TUY R4 DN 1" 1/4...]
COLLIER  →  P199600363  (score: 80%)  [COLLIER DE SERRAGE DN 44/47...]
TUYAU  →  P199600772  (score: 77%)  [TUYAU OSV DN75...]
643000  →  P199403555  (score: 77%)  [VIS TH GAL CL 8.8 M 12*40...]
4032185  →  P199680136  (score: 73%)  [DISQUE A LAMELLE 115*22.23 Z60 SPEC: BL2460/2025...]
7020096  →  P199662040  (score: 71%)  [GUANT DE TRAVAIL T10...]
920644000  →  P199403496  (score: 70%)  [VIS TH GAL 8.8 M 10*40...]
77600  →  P199602123  (score: 64%)  [CADNA BLOCUS LAITON 60MM ref 77600...]
DW36PT  →  P199681231  (score: 62%)  [JEUX TARRAUD M24...]
2019005  →  P199684214  (score: 62%)  [SHAKO UNION TECHNOPOLYMERE SPEC: BL/LA25/01983...]
3121  →  P199642013  (score: 61%)  [CHAINE ACIER 21-5MM...]
3787  →  P199662039  (score: 61%)  [ARALDIT 2*15ML...]
2110160  →  P199602050  (score: 57%)  [CADNA BLOCUS LAITON 60MM REF 2110160...]
81105TN  →  P199420414  (score: 56%)  [BUTEE A RLX CYLIND ref 81105TN SPEC: BL/LR25/06907...]
1019016  →  P199680439  (score: 54%)  [RIVET POP 4*12.7...]

In [59]:
sql_statements = []
for _, row in aliases_df.iterrows():
    # Use the supplier name from the invoice; you may adjust this
    supplier = 'BOUDRANT'  # change if needed
    sql = (
        f"INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) "
        f"VALUES ('{supplier}', '{row['external_ref']}', '{row['internal_ref']}', 'colab_gemini', NOW());"
    )
    sql_statements.append(sql)

print("\n-- SQL to seed aliases --\n")
print("\n".join(sql_statements))

-- SQL to seed aliases --

INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '8020137', 'P199680105', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'PU1080BL', 'P199681847', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'RACCORD', 'P199600771', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '8012599', 'P199692133', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'NKX25Z', 'P199420416', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'COLLIER', 'P199680428', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '6050004', 'P199680440', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'NPC8-04', 'P199450101', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'NPC12-02', 'P199450265', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'COLLIER', 'P199681803', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'BCF04H', 'P199403539', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'BCF05H', 'P199403542', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'FLEXSM', 'P199600774', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '1-947', 'P199680240', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'PU225S-04-S2', 'P199685061', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'TUYAU', 'P199600770', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'FLEXSM', 'P199600773', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '2030521', 'P199403517', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'NPC10-04', 'P199450136', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'OSV', 'P199680434', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'Z10100', 'P199450235', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '6030272-27', 'P199403654', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'TUYAU', 'P199680433', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'COLLIER', 'P199600363', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'TUYAU', 'P199600772', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '643000', 'P199403555', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '4032185', 'P199680136', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '7020096', 'P199662040', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '920644000', 'P199403496', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '77600', 'P199602123', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'DW36PT', 'P199681231', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '2019005', 'P199684214', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '3121', 'P199642013', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '3787', 'P199662039', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '2110160', 'P199602050', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '81105TN', 'P199420414', 'colab_gemini', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '1019016', 'P199680439', 'colab_gemini', NOW());

In [60]:
aliases_df.to_csv('/content/drive/MyDrive/alias_mappings.csv', index=False)
print("Exported to /content/drive/MyDrive/alias_mappings.csv")

Exported to /content/drive/MyDrive/alias_mappings.csv

In [61]:
sql = ""
for _, row in aliases_df.iterrows():
    sql += f"INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) "
    sql += f"VALUES ('BOUDRANT', '{row['external_ref']}', '{row['internal_ref']}', 'auto_colab', NOW());\n"
print(sql)

INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '8020137', 'P199680105', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'PU1080BL', 'P199681847', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'RACCORD', 'P199600771', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '8012599', 'P199692133', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'NKX25Z', 'P199420416', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'COLLIER', 'P199680428', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '6050004', 'P199680440', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'NPC8-04', 'P199450101', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'NPC12-02', 'P199450265', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'COLLIER', 'P199681803', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'BCF04H', 'P199403539', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'BCF05H', 'P199403542', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'FLEXSM', 'P199600774', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '1-947', 'P199680240', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'PU225S-04-S2', 'P199685061', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'TUYAU', 'P199600770', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'FLEXSM', 'P199600773', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '2030521', 'P199403517', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'NPC10-04', 'P199450136', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'OSV', 'P199680434', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'Z10100', 'P199450235', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '6030272-27', 'P199403654', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'TUYAU', 'P199680433', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'COLLIER', 'P199600363', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'TUYAU', 'P199600772', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '643000', 'P199403555', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '4032185', 'P199680136', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '7020096', 'P199662040', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '920644000', 'P199403496', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '77600', 'P199602123', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', 'DW36PT', 'P199681231', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '2019005', 'P199684214', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '3121', 'P199642013', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '3787', 'P199662039', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '2110160', 'P199602050', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '81105TN', 'P199420414', 'auto_colab', NOW());
INSERT INTO reference_aliases (supplier_name, external_ref, internal_ref, approved_by, approved_at) VALUES ('BOUDRANT', '1019016', 'P199680439', 'auto_colab', NOW());

In [62]:
# Display final aliases table
print("Final aliases (external → internal):")
display(aliases_df[['external_ref', 'internal_ref', 'designation', 'qty', 'prix', 'match_score']])

# Download the CSV file to your local machine
from google.colab import files
files.download('/content/drive/MyDrive/alias_mappings.csv')

# Save SQL to a file and download
sql_filename = '/content/alias_inserts.sql'
with open(sql_filename, 'w') as f:
    f.write("\n".join(sql_statements))
files.download(sql_filename)

Final aliases (external → internal):

,external_ref,internal_ref,designation,qty,prix,match_score
0,8020137,P199680105,DECAPANT 5L,1.0,30.300,100
1,PU1080BL,P199681847,CAM TUBE 10X8 BLEU,20.0,4.339,100
2,RACCORD,P199600771,RACCORD S16 male 1/2,8.0,12.000,100
3,8012599,P199692133,SILICONE SIKAFLEX CRISTAL,1.0,34.252,100
4,NKX25Z,P199420416,RLT A AIG AVEC BUTEE,4.0,242.200,100
5,COLLIER,P199680428,COLLIER DE SERRAGE A BOULON DN 80/85,4.0,15.000,95
6,6050004,P199680440,RIVET ALLU 4.8*22,250.0,0.098,94
7,NPC8-04,P199450101,SHAKO RACC DROIT 8 1/2,5.0,6.821,94
8,NPC12-02,P199450265,SHAKO RACC DROIT 12 1/4,10.0,6.207,94
9,COLLIER,P199681803,COLLIER DE SERRAGE A BOULON DN 23/35,10.0,4.000,92
10,BCF04H,P199403539,MECHE ACIER RECTIFIE 4MM,2.0,0.938,90
11,BCF05H,P199403542,MECHE ACIER RECTIFIE 5MM,5.0,1.366,90
12,FLEXSM,P199600774,"FLEX EAU R2AT DN 3/8"" LG 1000 F/FC 90°",2.0,69.000,90
13,1-947,P199680240,JEUX 9 CLE MALE LONG 1.5-10MM,1.0,49.132,90
14,PU225S-04-S2,P199685061,SHAKO ELECTROANNE 2/2 1/4,1.0,240.278,89
15,TUYAU,P199600770,TUYAU ARME DN 16,20.0,25.000,88
16,FLEXSM,P199600773,"FLEX DE GRAISSE DN 1/4"" LG 1260 F/FC 90°",2.0,79.500,87
17,2030521,P199403517,TIGE GALVA DE24,1.0,28.382,85
18,NPC10-04,P199450136,SHAKO RACC DROIT 10 1/2,5.0,7.752,85
19,OSV,P199680434,TUY GORGE OSV DN 38,10.0,15.000,85
20,Z10100,P199450235,SHAKO TEMPORISATEUR Z10100,1.0,109.943,84
21,6030272-27,P199403654,RONDELLE PLATE GALV M6/27,50.0,0.072,83
22,TUYAU,P199680433,"TUY R4 DN 1"" 1/4",20.0,50.000,82
23,COLLIER,P199600363,COLLIER DE SERRAGE DN 44/47,20.0,5.000,80
24,TUYAU,P199600772,TUYAU OSV DN75,10.0,30.000,77
25,643000,P199403555,VIS TH GAL CL 8.8 M 12*40,30.0,0.578,77
26,4032185,P199680136,DISQUE A LAMELLE 115*22.23 Z60 SPEC: BL2460/2025,2.0,4.695,73
27,7020096,P199662040,GUANT DE TRAVAIL T10,1.0,3.894,71
28,920644000,P199403496,VIS TH GAL 8.8 M 10*40,30.0,0.519,70
29,77600,P199602123,CADNA BLOCUS LAITON 60MM ref 77600,1.0,9.440,64
30,DW36PT,P199681231,JEUX TARRAUD M24,1.0,330.000,62
31,2019005,P199684214,SHAKO UNION TECHNOPOLYMERE SPEC: BL/LA25/01983,10.0,5.568,62
32,3121,P199642013,CHAINE ACIER 21-5MM,1.0,4.520,61
33,3787,P199662039,ARALDIT 2*15ML,1.0,32.303,61
34,2110160,P199602050,CADNA BLOCUS LAITON 60MM REF 2110160,2.0,45.081,57
35,81105TN,P199420414,BUTEE A RLX CYLIND ref 81105TN SPEC: BL/LR25/0...,4.0,122.341,56
36,1019016,P199680439,RIVET POP 4*12.7,1000.0,0.046,54

In [63]:
# Debug: inspect extraction from 20260302_12115701.pdf
debug_pdf = '20260302_12115701.pdf'
debug_df = df[df['source_pdf'] == debug_pdf]
print(f"Lines extracted from {debug_pdf}:")
print(f"Doc types: {debug_df['doc_type'].value_counts().to_dict()}")
display(debug_df[['page', 'doc_type', 'ref', 'designation', 'qty', 'prix_unitaire']])

Lines extracted from 20260302_12115701.pdf:
Doc types: {'BC': 12, 'FACTURE': 9}

,page,doc_type,ref,designation,qty,prix_unitaire
0,1,FACTURE,2019005,MW UNION = TECHNOPOLYMERE,10.0,5.568
1,1,FACTURE,NPC12-02,SHAKO RACCORD DROIT 12 1/4,10.0,6.207
2,1,FACTURE,NPC10-04,SHAKO RACC DROIT 10 1/2 EQ 2L01,5.0,7.752
3,1,FACTURE,NPC8-04,SHAKO RACCORD DROIT 8 1/2,5.0,6.821
4,1,FACTURE,PU1080BL,CAM TUBE 10X8 BLEU,20.0,4.339
5,1,FACTURE,PU225S-04-S2,SHAKO ELECTROVANNE NF 2/2 1/2,1.0,240.278
6,1,FACTURE,Z10100,SHAKO TEMPORISATEUR,1.0,109.943
7,1,FACTURE,81105 TN,BUTEE A RLX CYLINDRIQUE,4.0,122.341
8,1,FACTURE,NKX 25 Z,RLT A AIGUILLES AVEC BUTEE A B,4.0,242.200
9,2,BC,P199420414,BUTEE A RLX CYLIND ref 81105TN SPEC: BL/LR25/0...,4.0,122.341
10,2,BC,P199420416,RLT A AIG AVEC BUTEE ref NKX 25Z,10.0,242.200
11,2,BC,P199684214,SHAKO UNION TECHNOPOLYMERE SPEC: BL/LA25/01983,10.0,5.568
12,2,BC,P199450265,SHAKO RACC DROIT 12 1/4,10.0,6.207
13,2,BC,P199450136,SHAKO RACC DROIT 10 1/2,5.0,7.752
14,2,BC,P199450101,SHAKO RACC DROIT 8 1/2,5.0,6.821
15,2,BC,P199681847,CAM TUBE 10X8 BLEU,20.0,4.339
16,2,BC,P199685061,SHAKO ELECTROANNE 2/2 1/4,1.0,240.278
17,2,BC,P199450235,SHAKO TEMPORISATEUR Z10100,1.0,109.943
18,2,BC,P199541018,MW FR + lg1 REF 4684008,1.0,389.579
19,2,BC,P199684090,SHAKO MANO D40 G1/8 12BAR,1.0,15.506
20,2,BC,P199680443,BARREAU CLAVETTE H9 ACIER SPEC: BL/LC25/04527,2.0,11.685